spring.application.name=hospitalManagement

# DATABASE (POSTGRESQL) CONNECTION

# Updated to connect to the "Stocks" database
spring.datasource.url=jdbc:postgresql://localhost:5432/Stocks
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver


# create the database schema on startup.

spring.jpa.hibernate.ddl-auto=create

# Show SQL queries in the console log
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true